resources:
  containers:
  - container: swift40
    image: norionomura/swiftlint:swift-4.0
  - container: swift41
    image: norionomura/swiftlint:swift-4.1
  - container: swift42
    image: norionomura/swiftlint:swift-4.2

trigger:
- 1.0-branch
- swift40
- swift41
- swift42

jobs:
- job: swift40
  condition: not(in(variables['Build.SourceBranchName'], 'swift41', 'swift42'))
  pool:
    vmImage: 'Ubuntu 16.04'
  container: swift40
  steps:
    - script: swift build --package-path Libraries
- job: swift41
  condition: not(in(variables['Build.SourceBranchName'], 'swift40', 'swift42'))
  pool:
    vmImage: 'Ubuntu 16.04'
  container: swift41
  steps:
    - script: swift build --package-path Libraries
- job: swift42
  condition: not(in(variables['Build.SourceBranchName'], 'swift40', 'swift41'))
  pool:
    vmImage: 'Ubuntu 16.04'
  container: swift42
  steps:
    - script: swift build --package-path Libraries
