version: 2.1

commands:
  swiftlint:
    steps:
      - run: mkdir -p build/reports/
      - run: swiftlint lint --strict --reporter junit > build/reports/junit.xml
      - store_test_results:
          path: build/reports/

jobs:
  build_with_image:
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - run: apt-get update && apt-get install -y libsodium-dev
      - run: swift build -v

workflows:
  workflow:
    jobs:
      - build_with_image:
          name: swift-4.0.3-RELEASE
          image: norionomura/swiftlint:swift-4.0.3
          filters: { branches: { ignore: [swift41, swift42, swift, swift-tensorflow] } }
          post-steps: [swiftlint]
      - build_with_image:
          name: swift-4.1.3-RELEASE
          image: norionomura/swiftlint:swift-4.1.3
          filters: { branches: { ignore: [swift40, swift42, swift, swift-tensorflow] } }
          post-steps: [swiftlint]
      - build_with_image:
          name: swift-4.2.1-RELEASE
          image: norionomura/swiftlint:swift-4.2.1
          filters: { branches: { ignore: [swift40, swift41, swift, swift-tensorflow] } }
          post-steps: [swiftlint]
      - build_with_image:
          name: swift-nightly
          image: norionomura/swift:nightly
          filters: { branches: { ignore: [swift40, swift41, swift42, swift-tensorflow] } }
      - build_with_image:
          name: swift-tensorflow
          image: norionomura/swift-tensorflow
          filters: { branches: { ignore: [swift40, swift41, swift42, swift] } }
