aliases:
  - &steps-for-linux
    - checkout
    - run: apt-get update && apt-get install -y libsodium-dev
    - run: swift build

version: 2
jobs:
  linux_swift_4.0.3:
    docker:
      - image: norionomura/swift:403
    steps: *steps-for-linux

  linux_swift_4.1:
    docker:
      - image: norionomura/swift:41
    steps: *steps-for-linux

  linux_swift_4.2:
    docker:
      - image: norionomura/swift:20180418a
    steps: *steps-for-linux

workflows:
  version: 2
  workflow:
    jobs:
      - linux_swift_4.0.3
      - linux_swift_4.1
      - linux_swift_4.2
