aliases:
  - &steps-for-linux
    - checkout
    - run: apt-get update && apt-get install -y libsodium-dev
    - run: swift build
    - run: mkdir -p build/reports/
    - run: swiftlint lint --strict --reporter junit > build/reports/junit.xml
    - store_test_results:
        path: build/reports/
    - run: swift build --package-path Libraries

  - &steps-for-linux-without-swiftlint
    - checkout
    - run: apt-get update && apt-get install -y libsodium-dev
    - run: swift build
    - run: swift build --package-path Libraries

version: 2
jobs:
  linux_swift_4.0.3:
    docker:
      - image: norionomura/swiftlint:swift-4.0.3
    steps: *steps-for-linux

  linux_swift_4.1.2:
    docker:
      - image: norionomura/swiftlint:swift-4.1.2
    steps: *steps-for-linux

  linux_swift_4.2:
    docker:
      - image: norionomura/swift:swift-4.2-branch
    steps: *steps-for-linux-without-swiftlint

  linux_swift_nightly:
    docker:
      - image: norionomura/swift:nightly
    steps: *steps-for-linux-without-swiftlint

  linux_swift_tensorflow:
    docker:
      - image: norionomura/swift-tensorflow
    environment:
      USE_YAMS: no
    steps: *steps-for-linux-without-swiftlint

workflows:
  version: 2
  workflow:
    jobs:
      - linux_swift_4.0.3:
          filters:
            branches:
              ignore:
                - swift41
                - swift42
                - swift
                - swift-tensorflow
      - linux_swift_4.1.2:
          filters:
            branches:
              ignore:
                - swift40
                - swift42
                - swift
                - swift-tensorflow
      - linux_swift_4.2:
          filters:
            branches:
              ignore:
                - swift40
                - swift41
                - swift
                - swift-tensorflow
      - linux_swift_nightly:
          filters:
            branches:
              ignore:
                - swift40
                - swift41
                - swift42
                - swift-tensorflow
      - linux_swift_tensorflow:
          filters:
            branches:
              ignore:
                - swift40
                - swift41
                - swift42
                - swift
