version: 2.1

commands:
  swiftlint:
    steps:
      - run: mkdir -p build/reports/
      - run: swiftlint lint --strict --reporter junit > build/reports/junit.xml
      - store_test_results:
          path: build/reports/

jobs:
  build_with_image:
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - run: apt-get update && apt-get install -y libsodium-dev libssl-dev
      - run: swift build -c release

workflows:
  workflow:
    jobs:
      - build_with_image:
          name: Swift 5.0
          image: norionomura/swift:5.0
          filters: { branches: { ignore: [/swift.*/, /1.0.*] } }
