version: 2.1

commands:
  swiftlint:
    steps:
      - run: mkdir -p build/reports/
      - run: swiftlint lint --strict --reporter junit > build/reports/junit.xml
      - store_test_results:
          path: build/reports/

jobs:
  build_with_image:
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - run: apt-get update && apt-get install -y libsodium-dev
      - run: swift build -c release

workflows:
  workflow:
    jobs:
      - build_with_image:
          name: swift-4.2.2-RELEASE
          image: norionomura/swiftlint:swift-4.2.2
          filters: { branches: { ignore: [/swift.*/] } }
          post-steps: [swiftlint]
