version: 2.1

jobs:
  build_with_swiftlint_image:
    parameters:
      tag:
        type: string
    docker:
      - image: norionomura/swiftlint:<< parameters.tag >>
    steps:
      - checkout
      - run: apt-get update && apt-get install -y libsodium-dev
      - run: swift build
      - run: mkdir -p build/reports/
      - run: swiftlint lint --strict --reporter junit > build/reports/junit.xml
      - store_test_results:
          path: build/reports/

  build_with_swift_image:
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - run: apt-get update && apt-get install -y libsodium-dev
      - run: swift build

workflows:
  workflow:
    jobs:
      - build_with_swiftlint_image:
          tag: swift-4.0.3
          filters: { branches: { ignore: [swift41, swift42, swift, swift-tensorflow] } }
      - build_with_swiftlint_image:
          tag: swift-4.1.3
          filters: { branches: { ignore: [swift40, swift42, swift, swift-tensorflow] } }
      - build_with_swift_image:
          image: norionomura/swift:swift-4.2-branch
          filters: { branches: { ignore: [swift40, swift41, swift, swift-tensorflow] } }
      - build_with_swift_image:
          image: norionomura/swift:nightly
          filters: { branches: { ignore: [swift40, swift41, swift42, swift-tensorflow] } }
      - build_with_swift_image:
          image: norionomura/swift-tensorflow
          filters: { branches: { ignore: [swift40, swift41, swift42, swift] } }
