name: Swift

on:
  push:
    branches: [master]
    paths: 
      - '.github/workflows/swift.yml'
      - 'Package*'
      - 'Sources/**/*.swift'
      - 'Tests/**/*.swift'
  pull_request:
    paths: 
      - '.github/workflows/swift.yml'
      - 'Package*'
      - 'Sources/**/*.swift'
      - 'Tests/**/*.swift'

jobs:
  Swift:
    strategy:
      matrix:
        tag: ['5.0', '5.1']
    runs-on: ubuntu-latest
    container:
      image: norionomura/swift:${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v1
      - run: apt-get update && apt-get install -y libsodium-dev libssl-dev
      - run: swift build -c release
